### ISSUE TITLE
v1.2.0 was a breaking change

### ISSUE THREAD

**Issue by brandonkal** [ehmicky/fast-cartesian#1]
The title says it all. Going from a default export to a named export breaks code.

Next time please bump the major version when making breaking changes. You may wish to bump to 2.0.0 so others won't run into this issue when upgrading their dependencies.

**Comment by ehmicky** [comment]
Hi @brandonkal,

Sorry I did not know this package was used by others. I always follow semver but not if the library is only used by me. I usually check the "Used by" button for that purpose, but it seems like it missed your repository.

Knowing that it is used indeed (which is great, hope you like it), I will start following semver. I've just released [`2.0.0`](https://github.com/ehmicky/fast-cartesian/releases/tag/2.0.0). I'm also going to update the [`CHANGELOG`](https://github.com/ehmicky/fast-cartesian/blob/master/CHANGELOG.md) from now on.
