### ISSUE TITLE
Rename the files to mjs

### ISSUE THREAD

**Issue by stevefan1999-personal** [ehmicky/fast-cartesian#16]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

This prevents the module to be accidentally loaded in a CommonJS context since Node will resolve the ESM files by its extension, so we can mix both world

### Describe the solution you'd like

Just rename the source files to mjs

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @stevefan1999-personal, :wave: 

Thanks for your message. When using CommonJS, this module should be loaded using a dynamic `import()`. Using a static `import` of a ESM module from CommonJS is an error from the consumer, not the library. 
I do agree that preventing consumer errors is a good thing, and using `*.mjs` would achieve that. However, in this case, I think the instruction in the ["Install" section](https://github.com/ehmicky/fast-cartesian#install) of the `README` should be enough.

Thanks a lot for suggesting it though!

**Comment by albertodiazdorado** [comment]
In case anyone comes across this, you have experimental support for using ES modules in CJS with Node v22.

Take this example:
```js
// main.js
const fastCartesian = require('fast-cartesian').default

const result = fastCartesian([
    ['red', 'blue'],
    [1,2],
  ]);

console.log(result); // [ [ 'red', 1 ], [ 'red', 2 ], [ 'blue', 1 ], [ 'blue', 2 ] ]
```

Then we have:

```sh
$ node -v
v22.11.0
$ node main.js
Error [ERR_REQUIRE_ESM]: require() of ES Module ...
Instead change the require of ... in ... to a dynamic import() which is available in all CommonJS modules.
$ node --experimental-require-module main.js
[ [ 'red', 1 ], [ 'red', 2 ], [ 'blue', 1 ], [ 'blue', 2 ] ]
```
