### ISSUE TITLE
Is this module the fastest?

### ISSUE THREAD

**Issue by fisker** [ehmicky/fast-cartesian#2]
4 algorithms I wrote to test https://github.com/fisker/fast-cartesian-product/tree/master/src/algorithms

result:

```text
$ node -r esm benchmark/benchmarkify.js
================================
  Cartesian product algorithms
================================

Platform info:
==============
   Windows_NT 10.0.18362 x64
   Node.JS: 10.16.2
   V8: 6.8.275.32-node.54
   Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz × 8

Suite: sets: 256x1
√ Calculate From Index                860,483 rps
√ Dynamic Loop Function                40,865 rps
√ Indexes Array                       107,186 rps
√ Recursive                           243,579 rps
√ fast-cartesian(3rd-party)           170,112 rps

   Calculate From Index                 0%        (860,483 rps)   (avg: 1μs)
   Dynamic Loop Function           -95.25%         (40,865 rps)   (avg: 24μs)
   Indexes Array                   -87.54%        (107,186 rps)   (avg: 9μs)
   Recursive                       -71.69%        (243,579 rps)   (avg: 4μs)
   fast-cartesian(3rd-party)       -80.23%        (170,112 rps)   (avg: 5μs)
-----------------------------------------------------------------------

Suite: sets: 1x256
√ Calculate From Index                162,394 rps
√ Dynamic Loop Function               234,190 rps
√ Indexes Array                        76,094 rps
√ Recursive                           145,094 rps
√ fast-cartesian(3rd-party)            69,551 rps

   Calculate From Index            -30.66%        (162,394 rps)   (avg: 6μs)
   Dynamic Loop Function                0%        (234,190 rps)   (avg: 4μs)
   Indexes Array                   -67.51%         (76,094 rps)   (avg: 13μs)
   Recursive                       -38.04%        (145,094 rps)   (avg: 6μs)
   fast-cartesian(3rd-party)        -70.3%         (69,551 rps)   (avg: 14μs)
-----------------------------------------------------------------------

Suite: sets: 4x8
√ Calculate From Index                  4,292 rps
√ Dynamic Loop Function                10,656 rps
√ Indexes Array                         2,267 rps
√ Recursive                             6,919 rps
√ fast-cartesian(3rd-party)             4,726 rps

   Calculate From Index            -59.73%          (4,292 rps)   (avg: 233μs)
   Dynamic Loop Function                0%         (10,656 rps)   (avg: 93μs)
   Indexes Array                   -78.73%          (2,267 rps)   (avg: 441μs)
   Recursive                       -35.08%          (6,919 rps)   (avg: 144μs)
   fast-cartesian(3rd-party)       -55.65%          (4,726 rps)   (avg: 211μs)
-----------------------------------------------------------------------

Suite: sets: 8x4
√ Calculate From Index                     49 rps
√ Dynamic Loop Function                   111 rps
√ Indexes Array                            35 rps
√ Recursive                                54 rps
√ fast-cartesian(3rd-party)                40 rps

   Calculate From Index            -55.54%             (49 rps)   (avg: 20ms)
   Dynamic Loop Function                0%            (111 rps)   (avg: 9ms)
   Indexes Array                   -68.66%             (35 rps)   (avg: 28ms)
   Recursive                       -51.35%             (54 rps)   (avg: 18ms)
   fast-cartesian(3rd-party)       -63.51%             (40 rps)   (avg: 24ms)
-----------------------------------------------------------------------

Suite: sets: 2x16
√ Calculate From Index                113,161 rps
√ Dynamic Loop Function               213,381 rps
√ Indexes Array                        51,884 rps
√ Recursive                           130,157 rps
√ fast-cartesian(3rd-party)            82,105 rps

   Calculate From Index            -46.97%        (113,161 rps)   (avg: 8μs)
   Dynamic Loop Function                0%        (213,381 rps)   (avg: 4μs)
   Indexes Array                   -75.68%         (51,884 rps)   (avg: 19μs)
   Recursive                          -39%        (130,157 rps)   (avg: 7μs)
   fast-cartesian(3rd-party)       -61.52%         (82,105 rps)   (avg: 12μs)
-----------------------------------------------------------------------

Suite: sets: 16x2
√ Calculate From Index                     33 rps
√ Dynamic Loop Function                    77 rps
√ Indexes Array                            24 rps
√ Recursive                                40 rps
√ fast-cartesian(3rd-party)                39 rps

   Calculate From Index            -56.68%             (33 rps)   (avg: 30ms)
   Dynamic Loop Function                0%             (77 rps)   (avg: 13ms)
   Indexes Array                    -68.1%             (24 rps)   (avg: 40ms)
   Recursive                       -47.91%             (40 rps)   (avg: 25ms)
   fast-cartesian(3rd-party)       -48.62%             (39 rps)   (avg: 25ms)
-----------------------------------------------------------------------

Suite: sets with random length: [3, 6, 4, 6, 4]
√ Calculate From Index                  7,019 rps
√ Dynamic Loop Function                23,435 rps
√ Indexes Array                         4,308 rps
√ Recursive                            15,024 rps
√ fast-cartesian(3rd-party)            10,586 rps

   Calculate From Index            -70.05%          (7,019 rps)   (avg: 142μs)
   Dynamic Loop Function                0%         (23,435 rps)   (avg: 42μs)
   Indexes Array                   -81.62%          (4,308 rps)   (avg: 232μs)
   Recursive                       -35.89%         (15,024 rps)   (avg: 66μs)
   fast-cartesian(3rd-party)       -54.83%         (10,586 rps)   (avg: 94μs)
-----------------------------------------------------------------------

Done in 372.21s.
```

test against `calculate-from-index.js`(default export of `fast-cartesian-product`), this module is still not the fastest in some case

result:

```text
$ node -r esm benchmark/benchmarkify.js
================================
  Cartesian product algorithms
================================

Platform info:
==============
   Windows_NT 10.0.18362 x64
   Node.JS: 10.16.2
   V8: 6.8.275.32-node.54
   Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz × 8

Suite: sets: 256x1
√ Calculate From Index                771,100 rps
√ fast-cartesian(3rd-party)           163,695 rps

   Calculate From Index                 0%        (771,100 rps)   (avg: 1μs)
   fast-cartesian(3rd-party)       -78.77%        (163,695 rps)   (avg: 6μs)
-----------------------------------------------------------------------

Suite: sets: 1x256
√ Calculate From Index                156,300 rps
√ fast-cartesian(3rd-party)            77,008 rps

   Calculate From Index                 0%        (156,300 rps)   (avg: 6μs)
   fast-cartesian(3rd-party)       -50.73%         (77,008 rps)   (avg: 12μs)
-----------------------------------------------------------------------

Suite: sets: 4x8
√ Calculate From Index                  4,127 rps
√ fast-cartesian(3rd-party)             4,315 rps

   Calculate From Index             -4.36%          (4,127 rps)   (avg: 242μs)
   fast-cartesian(3rd-party)            0%          (4,315 rps)   (avg: 231μs)
-----------------------------------------------------------------------

Suite: sets: 8x4
√ Calculate From Index                     48 rps
√ fast-cartesian(3rd-party)                38 rps

   Calculate From Index                 0%             (48 rps)   (avg: 20ms)
   fast-cartesian(3rd-party)       -19.64%             (38 rps)   (avg: 26ms)
-----------------------------------------------------------------------

Suite: sets: 2x16
√ Calculate From Index                113,724 rps
√ fast-cartesian(3rd-party)            76,654 rps

   Calculate From Index                 0%        (113,724 rps)   (avg: 8μs)
   fast-cartesian(3rd-party)        -32.6%         (76,654 rps)   (avg: 13μs)
-----------------------------------------------------------------------

Suite: sets: 16x2
√ Calculate From Index                     32 rps
√ fast-cartesian(3rd-party)                40 rps

   Calculate From Index            -19.19%             (32 rps)   (avg: 30ms)
   fast-cartesian(3rd-party)            0%             (40 rps)   (avg: 24ms)
-----------------------------------------------------------------------

Suite: sets with random length: [4, 4, 2, 5, 6]
√ Calculate From Index                 12,299 rps
√ fast-cartesian(3rd-party)            18,014 rps

   Calculate From Index            -31.73%         (12,299 rps)   (avg: 81μs)
   fast-cartesian(3rd-party)            0%         (18,014 rps)   (avg: 55μs)
-----------------------------------------------------------------------

Done in 156.88s.
```

**Comment by fisker** [comment]
In theory `generated loop function` has to be the fastest, but I won't use that, you can say this module is fast, but not the fastest

**Comment by ehmicky** [comment]
Hi @fisker, could you please share your benchmarking code so I can reproduce those results on my machine? 

The [benchmarks](https://github.com/fisker/fast-cartesian-product/blob/master/benchmark/algorithms.js) here do not show how you're importing/calling `fast-cartesian`.

**Comment by fisker** [comment]
checkout `https://github.com/fisker/fast-cartesian-product` modify `/benchmark/benchmarkify.js`  push your module to algorithms 

```js
algorithms.push({
  name: 'any name',
  fn(args) {
    yours(...args)
  }
})
```

run 

```bash
yarn benchmark2
```

**Comment by ehmicky** [comment]
Correct me if I'm wrong but you're calling `fast-cartesian` with an intermediate step (the `fn` function that forwards to `yours` and does an array spread). Whereas you're calling your own code without that intermediate step. It should only have few nanoseconds of difference, but it would be more accurate to add an arrow function to call your own code to make it more comparable.

**Comment by fisker** [comment]
yes, there is tiny difference, you can also spread in my modules to test

**Comment by fisker** [comment]
like this file `https://github.com/fisker/fast-cartesian-product/blob/ba948283eaac694ea9be1bbfbf731c87867fe5ad/src/algorithms/calculate-from-index.js#L1`

you can change to 

```js
function product(...sets) {
```

but should modify the test code

**Comment by ehmicky** [comment]
Could you please release your latest commit so I can benchmark against it?

I find `benchmarkify` to have lots of issues when it comes to both precision and accuracy. The benchmarking library I am using is [fixing those problems](https://github.com/ehmicky/spyd/blob/master/docs/algorithm.md).

**Comment by fisker** [comment]
use `https://github.com/fisker/fast-cartesian-product/blob/master/benchmark/index.js` which runs `benchmark`, if you do't trust `benchmarkify`

I also noticed you have a `validateArray` check, It's OK to remove it in yours to test

**Comment by fisker** [comment]
you can use your test case against `fast-cartesian-product@1.0.0`, but the fastest `dynamic-loop-function.js` is not bundled

**Comment by ehmicky** [comment]
I don't trust `benchmark.js` either, although they are going much further than `benchmarkify` to reduce some of the problems above.

Validation is part of the code run by end users, it should not be removed as it accounts for code speed.

Could you make a release with the different algorithms? Sometimes packaging/bundling might slow code down. I would like to check against the code that's actually shipped to end users.

**Comment by fisker** [comment]
I'm not going to do that, I wrote those algorithms just for fun.

`recursive`(mostly your algorithm) is great, but I like the `calculate-from-index` algorithm, I will only export `calculate-from-index` algorithm for now

**Comment by ehmicky** [comment]
Just to confirm, `2x4` means `cartesian([0,1,2,3], [0,1,2,3])`, `4x2` means `cartesian([0, 1], [0, 1], [0, 1], [0, 1])`, correct?

I.e. `Array.from({ length: width }, () => Array.from({ length: height }, (value, index) => index))`

When I say make a release, it does not have to be published on your latest npm tag, it can be a separate tag. Not sure why you would not want to do this, unless you think it might give you different results.

**Comment by fisker** [comment]
I think I can do that

**Comment by fisker** [comment]
branch `temp/algorithms` boundled file '/lib/index.js', I also use spread for you to test

exports 

https://github.com/fisker/fast-cartesian-product/blob/temp/algorithms/lib/index.js#L240-L243

**Comment by ehmicky** [comment]
What I meant is I would like to benchmark those different algorithms but after they have been bundled, i.e. how the end user would actually execute them.

**Comment by fisker** [comment]
```js
const {algorithm1} = require('lib/index')

algorithm1([1,2], [3,4])
```

I don't know what do you mean

**Comment by ehmicky** [comment]
The code shipped to npm by `fast-cartesian-product` is bundled. I would like to execute benchmarks against this, and not against the source code.

**Comment by ehmicky** [comment]
I think there might be something off with your benchmark setup. I've tried the following benchmark with no benchmark library to abstract differences due to benchmark setup, and I get quite different results.

```js
const fastCartesianProduct = require('fast-cartesian-product')
const fastCartesian = require('fast-cartesian')

const width = Number(process.argv[2])
const height = Number(process.argv[3])
const loops = Number(process.argv[4])

const args = Array.from({ length: width }, () =>
  Array.from({ length: height }, (value, index) => index),
)

const algorithms = [
  { name: 'fast-cartesian', fn: args => cartesianArray(...args) },
  { name: 'fast-cartesian-product', fn: args => fastCartesianProduct(args) },
]

algorithms.forEach(({ name, fn }) => {
  let repeat = loops
  const start = process.hrtime.bigint()

  while (repeat--) {
    fn(args)
  }

  const duration = Number(process.hrtime.bigint() - start) / 1e6
  console.log(
    `${width}x${height} (${loops.toLocaleString()} loops)`,
    name,
    `${Math.round(duration)}ms`,
  )
})
```

Above you pasted:

```
Suite: sets: 4x8
√ Calculate From Index                  4,127 rps
√ fast-cartesian(3rd-party)             4,315 rps

   Calculate From Index             -4.36%          (4,127 rps)   (avg: 242μs)
   fast-cartesian(3rd-party)            0%          (4,315 rps)   (avg: 231μs)

```

**Comment by ehmicky** [comment]
I think there might be something off with your benchmark setup. I've tried the following benchmarks. I haven't used any benchmark library to abstract differences due to benchmark setup.

```js
const { cartesianArray: fastCartesian } = require('fast-cartesian')
const fastCartesianProduct = require('fast-cartesian-product')

const width = Number(process.argv[2])
const height = Number(process.argv[3])
const loops = Number(process.argv[4])

const args = Array.from({ length: width }, () =>
  Array.from({ length: height }, (value, index) => index),
)

const algorithms = [
  { name: 'fast-cartesian', fn: args => fastCartesian(...args) },
  { name: 'fast-cartesian-product', fn: args => fastCartesianProduct(args) },
]

algorithms.forEach(({ name, fn }) => {
  let repeat = loops
  const start = process.hrtime.bigint()

  while (repeat--) {
    fn(args)
  }

  const duration = Number(process.hrtime.bigint() - start) / loops / 1e3
  console.log(
    `${width}x${height} (${loops.toLocaleString()} loops)`,
    name,
    `${Math.round(duration)}μs`,
  )
})
```

Your benchmarks:

```
Suite: sets: 4x8
√ Calculate From Index                  4,127 rps
√ fast-cartesian(3rd-party)             4,315 rps

   Calculate From Index             -4.36%          (4,127 rps)   (avg: 242μs)
   fast-cartesian(3rd-party)            0%          (4,315 rps)   (avg: 231μs)

Suite: sets: 8x4
√ Calculate From Index                     48 rps
√ fast-cartesian(3rd-party)                38 rps

   Calculate From Index                 0%             (48 rps)   (avg: 20ms)
   fast-cartesian(3rd-party)       -19.64%             (38 rps)   (avg: 26ms)
```

My benchmarks:

```
> node benchmark.js 4 8 1e5
4x8 (100,000 loops) fast-cartesian 83μs
4x8 (100,000 loops) fast-cartesian-product 143μs

> node benchmark.js 8 4 1e3
8x4 (1,000 loops) fast-cartesian 2369μs
8x4 (1,000 loops) fast-cartesian-product 5491μs
```

In your benchmarks, `fast-cartesian` is about the same speed. In my benchmarks, it is twice faster.

Also the average speed is very different (e.g. `26ms` vs `2.4ms`).

Could you run the above file and see if you get similar results?

**Comment by fisker** [comment]
feel free to edit any code on https://github.com/fisker/cartesian-product-algorithms-benchmark

I won't comment here any more

**Comment by fisker** [comment]
results shows on actions  https://github.com/fisker/cartesian-product-algorithms-benchmark/actions

**Comment by ehmicky** [comment]
The CI results do show similar results that the one I just posted, i.e. that `fast-cartesian` is about twice faster than the default `fast-cartesian-product`. There is definitely something wrong in your initial benchmark setup as results were quite different.

On the other hand, your second algorithm using `new Function()` was faster indeed. I actually used that algorithm as well previously but had concerns over V8 optimization weirdness of `new Function()`. I have updated the code to use a similar approach and now `fast-cartesian` and `fast-cartesian-product` are [roughly as fast as each other](https://github.com/fisker/cartesian-product-algorithms-benchmark/runs/199355916). Higher number of repeats gives more precise benchmarks, so I am not linking to the [latest commit that halves them](https://github.com/fisker/cartesian-product-algorithms-benchmark/commit/1f4ab63b625aa45b4736b7481a2ed64723ad353b).

Note that this is for Node 12. `fast-cartesian` is a little slower on Node 10, but that's ok since being the fastest on the latest Node version matters more to me.

Now the code on `cartesian-product-algorithms-benchmark` uses a simple `for` loop. While simple and easy to trust, there are [lots of issues](https://github.com/ehmicky/spyd/blob/master/docs/algorithm.md) with this approach. The benchmarking library `spyd` is fixing this. When using `spyd`, I get the following results which show `fast-cartesian` as being very slightly faster:

```
fast-cartesian           | 1 array   | median   868μs | mean   940μs | min   791μs | max  1479μs | deviation  ±161μs
fast-cartesian-product-2 | 1 array   | median   940μs | mean   950μs | min   775μs | max  1491μs | deviation  ±163μs
fast-cartesian-product   | 1 array   | median  1127μs | mean  1190μs | min  1003μs | max  2107μs | deviation  ±201μs
fast-cartesian           | 2 arrays  | median  1023μs | mean  1400μs | min   842μs | max  3646μs | deviation  ±836μs
fast-cartesian-product-2 | 2 arrays  | median  1024μs | mean  1383μs | min   836μs | max  3653μs | deviation  ±819μs
fast-cartesian-product   | 2 arrays  | median  1480μs | mean  1897μs | min  1356μs | max  4285μs | deviation  ±812μs
fast-cartesian           | 4 arrays  | median  1221μs | mean  2518μs | min   952μs | max  6156μs | deviation ±1662μs
fast-cartesian-product-2 | 4 arrays  | median  1232μs | mean  2498μs | min   976μs | max  6152μs | deviation ±1605μs
fast-cartesian-product   | 4 arrays  | median  2609μs | mean  3836μs | min  2245μs | max  7743μs | deviation ±1640μs
fast-cartesian           | 8 arrays  | median  1426μs | mean  1460μs | min  1157μs | max  1883μs | deviation  ±223μs
fast-cartesian-product-2 | 8 arrays  | median  1433μs | mean  1475μs | min  1175μs | max  1901μs | deviation  ±219μs
fast-cartesian-product   | 8 arrays  | median  4480μs | mean  4540μs | min  4036μs | max  5042μs | deviation  ±226μs
fast-cartesian           | 16 arrays | median  3488μs | mean  4056μs | min  1672μs | max  8756μs | deviation ±1802μs
fast-cartesian-product-2 | 16 arrays | median  3575μs | mean  4204μs | min  1789μs | max  8666μs | deviation ±1821μs
fast-cartesian-product   | 16 arrays | median 10471μs | mean 10977μs | min  8352μs | max 15053μs | deviation ±1760μs
```

**Comment by fisker** [comment]
you can repeat as many times as you  want  ,I just thought github actions may has time limit, so I reduce the repeats, I made this second one just to prove your module is not the fastest, I never thought you will change your code to current version  there is no meaning to compare them  they  are  basically the same, as I said before recursive is  a great algorithm, but  definitely not the  fastest, nothing  should  say  it self  the  most xxx.  suggest you  change that  to  one of the fastest or faster than  most modules.  I  can't accept that. If i want  something  fastest I can  just  run  tests on  all of

**Comment by fisker** [comment]
you can repeat as many times as you  want  ,I just thought github actions may has time limit, so I reduce the repeats, I made this second one just to prove your module is not the fastest, I never thought you will change your code to current version  there is no meaning to compare them  they  are  basically the same, as I said before recursive is  a great algorithm, but  definitely not the  fastest, nothing  should  say  it self  the  most xxx.  suggest you  change that  to  "one of the fastest" or "faster than  most modules".  I  can't accept that you saying  your module is the fastest in readme. If i want  something best can I just  run  tests on  all alternative export  the  best one ?

there  is  one more  thing  you  should  know there is a limitation of  depth on  for  loop , this  new  Function algorithm is  not good if  I remember current it  can't  even  work  on  a  1024x1 array, I suggest you  use your old  algorithm that  is  fast  enough

**Comment by fisker** [comment]
I made the `fast-cartesian-product` module just want to introduce the calculate-from-index algorithm which I have using for years, and it's coming up all by myself. I was not trying to make it  fast at  the first place, I was trying to make a zero memory and infinity combinationes lib which is now `power-cartesian-product`.

**Comment by ehmicky** [comment]
Yes you're right, there's a maximum call stack error when passing more than 604 arguments (on my machine). Note that:
  - this is only affecting the number of arguments passed to `fast-cartesian`. The arrays themselves can still be infinitely large (when using the iterable methods).
  - this is only affecting the `array()` method. The `iterate()` method has no such limits.

The new code is very similar indeed, but slightly improved. For example I use a `for of` loop instead of a regular `for` and some other minor optimizations, which explains why it's slightly faster. That new algorithm is used in the latest version of `fast-cartesian`. Per the benchmarks posted in my previous message, `fast-cartesian` is the fastest implementation at the moment.

> I can't accept that you saying your module is the fastest in readme.

Let's keep it courteous and in line with the [code of conduct](https://github.com/ehmicky/fast-cartesian/blob/master/CODE_OF_CONDUCT.md#our-standards).

**Comment by fisker** [comment]
It's not improve, we have different target, did you notice I use `var` in function body, I want it run on more old engines

**Comment by ehmicky** [comment]
I meant "improved" from a performance perspective. The supported platforms, features, validation, documentation, etc. are different indeed.
