### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by marcelgerber** [ehmicky/fast-cartesian#6]
**Which problem is this feature request solving?**

Hi @ehmicky! We would love to use your great little tool in https://github.com/owid/owid-grapher so it can power https://ourworldindata.org. However, since our code base is entirely written in TypeScript, it would make our lives easier if you could add TS type definitions (`.d.ts`) to this repo and to the published package on npm.

**Describe alternatives you've considered**

Of course, type definitions could also be added to https://github.com/DefinitelyTyped/DefinitelyTyped/, but I find it easier to work with types that are provided with the library itself.

**Can you submit a pull request?**

Yes, could do that if you're interested.

**Comment by ehmicky** [comment]
Hi @MarcelGerber,

That would be awesome! 
Would you like to send a PR?

**Comment by ehmicky** [comment]
Fixed in #7.

**Comment by ehmicky** [comment]
Published in [`5.1.0`](https://github.com/ehmicky/fast-cartesian/releases/tag/5.1.0).

**Comment by marcelgerber** [comment]
Thank you for the quick publishing, we are now using this library for https://ourworldindata.org (which is hosted on Netlify, btw :) ) and have seen an almost 50-fold performance increase from the naive method we used before! (https://github.com/owid/owid-grapher/pull/783)

**Comment by ehmicky** [comment]
That's great! :tada: 

I've spent quite some time fine-tuning the performance of this library and comparing it with similar alternatives. :)

Would it be ok for me to add your comment as a testimonial to the `README`? PR at https://github.com/ehmicky/fast-cartesian/pull/8, please feel free to review it!

**Comment by ehmicky** [comment]
@all-contributors-bot Would you please add @MarcelGerber for adding this code?

**Comment by ehmicky** [comment]
@all-contributors Would you please add @MarcelGerber for adding this code?
